import Head from "next/head";
import { useState } from "react";

import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import Banner from "../components/Banner";

import Menu from "../components/Menu";
import PortfolioDisplay from "../components/PortfolioDisplay";
import PopUp from "../components/PopUp";
gsap.registerPlugin(ScrollTrigger);

export default function Home() {
  const [displayMenu, setDisplayMenu] = useState(false);
  const [displayPopUp, setDisplayPopUp] = useState(false);
  const [vidUrl, setVidUrl] = useState("");
  const [playing, setPlaying] = useState(false);

  return (
    <div className="">
      <Head>
        <title>Creative0x</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Nav displayMenu={displayMenu} setDisplayMenu={setDisplayMenu} /> */}
      <PopUp
        displayPopUp={displayPopUp}
        setDisplayPopUp={setDisplayPopUp}
        vidUrl={vidUrl}
        playing={playing}
        setPlaying={setPlaying}
      />
      <Menu
        displayMenu={displayMenu}
        setDisplayMenu={setDisplayMenu}
        vidUrl={vidUrl}
        setVidUrl={setVidUrl}
        displayPopUp={displayPopUp}
        setDisplayPopUp={setDisplayPopUp}
        setPlaying={setPlaying}
      />
      <PortfolioDisplay
        displayMenu={displayMenu}
        setDisplayMenu={setDisplayMenu}
        vidUrl={vidUrl}
        setVidUrl={setVidUrl}
      />
      <Banner displayMenu={displayMenu} setDisplayMenu={setDisplayMenu} />

      {/* <WebPortfolio /> */}
      {/* <Backdrop />
      <FilmPortfolio />
      <Contact /> */}
    </div>
  );
}
