import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import { Parallax, ParallaxLayer } from "@react-spring/parallax";

import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import Banner from "../components/Banner";
import Nav from "../components/Nav";
import WebPortfolio from "../components/WebPortfolio";
import Image from "next/image";
import Backdrop from "../components/Backdrop";
import FilmPortfolio from "../components/FilmPortfolio";
import Contact from "../components/Contact";

gsap.registerPlugin(ScrollTrigger);

export default function Home() {
  const [displayMenu, setDisplayMenu] = useState(false);

  return (
    <div>
      <Head>
        <title>Creative0x</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav displayMenu={displayMenu} setDisplayMenu={setDisplayMenu} />
      <Banner displayMenu={displayMenu} setDisplayMenu={setDisplayMenu} />
      <WebPortfolio />
      <Backdrop />
      <FilmPortfolio />
      <Contact />
    </div>
  );
}
